### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by arendondiosa** [ColombiaPython/pyday-pereira-2019#10]
- [x] Título
- [x] Detalle de la sección
- [x] Agregar Agenda. _Sugerencia: Partir el día en dos_

**Comment by Nany262** [comment]
Se traduce el titulo
    Se escribe un nuevo detalle de sección ( propuesta, proximo a cambiar)
    Se agrega la propuesta de agenda

Pendiente por aprobación @arendondiosa
